FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as app-builder
WORKDIR /app
COPY src .
WORKDIR /app/BirthdayAssistant.Telegram
RUN dotnet publish BirthdayAssistant.Telegram.fsproj -c Release -o publish

# Run tests here

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=app-builder /app/BirthdayAssistant.Telegram/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "BirthdayAssistant.Telegram.dll"]